name: 'Report SimpleCov Coverage'
description: 'Upload SimpleCov Report to S3 so that we can check it in the comments of Pull Request'
runs:
  using: composite
  steps:
    - name: Test S3 Access
      run: aws s3 ls s3://
      shell: bash
