name: 'Report SimpleCov Coverage'
description: 'Upload SimpleCov Report to S3 so that we can check it in the comments of Pull Request'
runs:
  using: composite
  steps:
    - name: Hello World
      run: echo 'Hello World'
      shell: bash
