name: 'Report SimpleCov Coverage'
description: 'Upload SimpleCov Report to S3 so that we can check it in the comments of Pull Request'
runs:
  using: composite
  steps:
    - name: Install awscli
      run: |
        curl -sf "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        aws --version
      shell: bash
