name: simplecov-report / test-without-last-run
on:
  pull_request:
jobs:
  simplecov-report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # GitHub OIDC with AWS
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./sample_simplecov
      - name: Run rspec
        run: bundle exec rspec
        working-directory: ./sample_simplecov
      - run: rm sample_simplecov/coverage/.last_run.json
      - uses: ./
        with:
          coverage_path: sample_simplecov/coverage
          upload_destination: simplecov_coverage_without_last_run
          upload_bucket: snowfield702-sample
          comment: Please check coverage report (nothing .last_run.json)
          domain: snowfield702-sample.s3.ap-northeast-1.amazonaws.com
