name: simplecov-report / test
on:
  push:
jobs:
  simplecov-report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # GitHub OIDC with AWS
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - uses: ./
